language: php

php:
  - 7.2
  - 7.4

services:
  - postgresql
  - mysql

env:
  matrix:
    - DB=mysql DB_URL='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql DB_URL='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite DB_URL='sqlite:///:memory:'

  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.3
      env: STATIC_ANALYSIS=1 DEFAULT=0

    - php: 7.2
      env: PREFER_LOWEST=1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.4 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer update --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

  - if [[ $STATIC_ANALYSIS = 1 ]]; then composer require phpstan/phpstan:^0.12 psalm/phar:^3.7; fi

script:
  - if [[ $TRAVIS_PHP_VERSION == 7.4 ]]; then vendor/bin/phpunit; fi
  - if [[ $TRAVIS_PHP_VERSION != 7.4 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $STATIC_ANALYSIS = 1 ]]; then vendor/bin/phpstan.phar analyse src && vendor/bin/psalm.phar --show-info=false; fi

after_success:
  - if [[ $CODECOVERAGE ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
